spring.application.name=JawboneBackend

# Spring Datasource Configuration
spring.datasource.url=jdbc:sqlite:jawbone.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# H2 Console Configuration
spring.h2.console.enabled=true

# Hibernate/JPA Configuration
# Use the correct dialect class, e.g., org.hibernate.community.dialect.SQLiteDialect
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



